# Generated by Django 3.1.5 on 2021-02-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Data',
        ),
    ]
