# Generated by Django 3.1.5 on 2021-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210227_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DigitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.CharField(max_length=200)),
                ('aplha', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
