# Generated by Django 3.1.5 on 2021-02-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210227_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitdata',
            name='aplha',
        ),
    ]
